name: "godot-ci export"
on: 
  push:
    tags:
    - 'v*'

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: proj-befrielsen
  PROJECT_FOLDER: project

jobs:
  export-windows:
    permissions:
      contents: write
    name: Windows Export
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: .NET installation
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Windows Build
        run: |
          Invoke-WebRequest https://github.com/ZeroFkinDevs/godot/releases/download/zfd-v8/zerofkndevs-godot.zip -OutFile zerofkndevs-godot.zip
          Expand-Archive ./zerofkndevs-godot.zip -DestinationPath ./
          New-Item -ItemType Directory -Path $env:APPDATA/Roaming/Godot/export_templates/4.3.stable.mono -Force
          Copy-Item ./godot.windows.template_release.x86_64.mono.exe -Destination $env:APPDATA/Roaming/Godot/export_templates/4.3.stable.mono/windows_release_x86_64.exe
          Copy-Item ./GodotSharp -Destination $env:APPDATA/Roaming/Godot/export_templates/4.3.stable.mono/GodotSharp -Recurse
          Copy-Item ./godot.windows.editor.x86_64.mono.exe -Destination ./godot.exe -Recurse

          New-Item -ItemType Directory -Path ./build/windows -Force
          cd $PROJECT_FOLDER
          Start-Process -FilePath "../godot.exe" -ArgumentList "--headless --verbose --import --quit-after 10" -NoNewWindow -Wait
          Start-Process -FilePath "../godot.exe" -ArgumentList "--headless","--verbose","--export-release","Windows Desktop","../build/windows/$EXPORT_NAME.exe" -NoNewWindow -Wait
          cd ..
          Compress-Archive -Path ./build/windows/* -Destination ./build/Befrielsen_Windows_x64.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            build/Befrielsen_Windows_x64.zip