name: "godot-ci export"
on: 
  push:
    tags:
    - 'v*'

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: proj-befrielsen
  PROJECT_PATH: project

jobs:
  export-windows:
    permissions:
      contents: write
    name: Windows Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:mono-4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: .NET installation
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      - name: Setup
        run: |
          wget https://github.com/ZeroFkinDevs/godot/releases/download/zfd-v9/zerofkndevs-godot-linux.zip
          unzip zerofkndevs-godot-linux.zip
          mkdir windows
          cd windows
          wget https://github.com/ZeroFkinDevs/godot/releases/download/zfd-v9/zerofkndevs-godot-windows.zip
          unzip zerofkndevs-godot-windows.zip
          mkdir -v -p ~/.local/share/godot/templates/4.3.stable.mono
          cp ./godot.windows.template_release.x86_64.mono.exe ~/.local/share/godot/templates/4.3.stable.mono/windows_release_x86_64.exe
          cp -r ./GodotSharp ~/.local/share/godot/templates/4.3.stable.mono/GodotSharp

          

      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          "$EXPORT_DIR/../godot.linuxbsd.editor.x86_64.mono" --headless --verbose --import --quit-after 10
          "$EXPORT_DIR/../godot.linuxbsd.editor.x86_64.mono" --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
          cd "$EXPORT_DIR/windows"
          zip -r "../Befrielsen_Windows_x64.zip" *
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            build/Befrielsen_Windows_x64.zip